---
title: 2Lig
timezone: America/Sao_Paulo
collections:
  testimonials:
    title: Depoimentos
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  areas:
    title: √Åreas
    output: true
baseurl: 
email: jonas@2lig.com.br
skype: jonasrj@hotmail.com
tel: "+55 21 99998-1488"
highlighter: rouge
markdown: kramdown
analytics: UA-83979019-1
compress_html:
  clippings:
  - html
  - div
  - p
  - ul
  - td
  - h1
  - h2
  - h3
  - h4
  - link
  - meta
  - footer
  - nav
  - img
  - header
  - hr
  - br
  - head
  - style
  - li
  - ul
  - ol
  - time
  - main
  - script
  - title
  comments:
  - "<!-- "
  - " -->"
  endings:
  - all
  ignore:
    envs:
    - local
  blanklines: false
  profile: false
sass:
  style: compressed
exclude:
- README.md
